version: '3.8'

services:
  postgres:
    build:
      context: postgres
      dockerfile: Dockerfile
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=pass
    volumes:
      - "db-data:/var/lib/postgresql/data"

  app:
    build:
      context: ..
      dockerfile: ./Dockerfile
    environment:
      - PORT=8091
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=pass
    image: 'product-management'
    ports:
      - 8091:8091
    depends_on:
      - postgres 
        
volumes:
   db-data: